sha1: 364de35cb5d94da6f3545951277acd89e8796e69
options:
  basename: MENU/MAINMENU.PRG
  target_path: data/MENU/MAINMENU.PRG
  elf_path: build/data/MENU/MAINMENU.PRG.elf
  asm_path: build/src/MENU/MAINMENU.PRG
  src_path: src/MENU/MAINMENU.PRG
  asset_path: build/assets/MENU/MAINMENU.PRG
  ld_script_path: build/config/MENU/MAINMENU.PRG/link.ld
  symbol_addrs_path: 
    - config/MENU/MAINMENU.PRG/symbol_addrs.txt
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
    - config/MENU/MENU0.PRG/symbol_addrs.txt
    - config/MENU/MENU1.PRG/symbol_addrs.txt
    - config/MENU/MENU2.PRG/symbol_addrs.txt
    - config/MENU/MENU3.PRG/symbol_addrs.txt
    - config/MENU/MENU4.PRG/symbol_addrs.txt
    - config/MENU/MENU5.PRG/symbol_addrs.txt
    - config/MENU/MENU7.PRG/symbol_addrs.txt
    - config/MENU/MENU8.PRG/symbol_addrs.txt
    - config/MENU/MENU9.PRG/symbol_addrs.txt
    - config/MENU/MENUB.PRG/symbol_addrs.txt
    - config/MENU/MENUC.PRG/symbol_addrs.txt
    - config/MENU/MENUD.PRG/symbol_addrs.txt
    - config/MENU/MENUE.PRG/symbol_addrs.txt
    - config/MENU/MENUF.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/MENU/MAINMENU.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MAINMENU.PRG/undefined_syms_auto.txt
  subalign: 4

segments:
  - start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
      - [0x00, .rodata, C48]
      - [0x12C, .rodata, 413C]
      - [0x1F8, .rodata, 58EC]
      - [0x224, c]
      - [0xC48, c]
      - [0x413C, c]
      - [0x58EC, c]
      - [0x8C10, data]
  - [0x8D79]
